
import app.modulos.cliente.ActualizarCliente;
import app.modulos.cliente.GuardarCliente;
import app.modulos.cliente.ListarCliente;
import app.modulos.tipoIdentificacion.ListarTipoIdentificacion;
import app.modulos.usuario.ActualizarUsuario;
import app.modulos.usuario.GuardarUsuario;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Josh
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g)
            {
                g.drawImage(new ImageIcon(getClass().getResource("/recursos/imagenes/bg-system.jpg")).getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        mInicio = new javax.swing.JMenu();
        mRegistrarUsuario = new javax.swing.JMenuItem();
        mActualizarUsuario = new javax.swing.JMenuItem();
        opGrupo = new javax.swing.JMenuItem();
        opPeriodo = new javax.swing.JMenuItem();
        opCarrera = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        mMatricula = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        mEstudiante = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        mRegistrarCliente = new javax.swing.JMenuItem();
        mActualizarCliente = new javax.swing.JMenuItem();
        mListarClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-system-16.png"))); // NOI18N
        mInicio.setText("Inicio");
        mInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-staff-16.png"))); // NOI18N
        mRegistrarUsuario.setMnemonic('o');
        mRegistrarUsuario.setText("Crear Usuario");
        mRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarUsuarioActionPerformed(evt);
            }
        });
        mInicio.add(mRegistrarUsuario);

        mActualizarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-staff-16.png"))); // NOI18N
        mActualizarUsuario.setMnemonic('s');
        mActualizarUsuario.setText("Actualizar Usuario");
        mActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActualizarUsuarioActionPerformed(evt);
            }
        });
        mInicio.add(mActualizarUsuario);

        opGrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-user-groups-16.png"))); // NOI18N
        opGrupo.setMnemonic('a');
        opGrupo.setText("Grupos");
        mInicio.add(opGrupo);

        opPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-sand-timer-16.png"))); // NOI18N
        opPeriodo.setText("Periodos");
        mInicio.add(opPeriodo);

        opCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-calendar-16.png"))); // NOI18N
        opCarrera.setText("Carreras");
        mInicio.add(opCarrera);

        exitMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-close-program-16.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mInicio.add(exitMenuItem);

        menuBar.add(mInicio);

        mMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-bookmark-16.png"))); // NOI18N
        mMatricula.setMnemonic('e');
        mMatricula.setText("Matrículas");
        mMatricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        mMatricula.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        mMatricula.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        mMatricula.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        mMatricula.add(deleteMenuItem);

        menuBar.add(mMatricula);

        mEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-user-account-16.png"))); // NOI18N
        mEstudiante.setMnemonic('h');
        mEstudiante.setText("Estudiantes");
        mEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        mEstudiante.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        mEstudiante.add(aboutMenuItem);

        menuBar.add(mEstudiante);

        mClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-administrator-male-16.png"))); // NOI18N
        mClientes.setText("Clientes");
        mClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-save-16.png"))); // NOI18N
        mRegistrarCliente.setText("Registrar");
        mRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarClienteActionPerformed(evt);
            }
        });
        mClientes.add(mRegistrarCliente);

        mActualizarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-edit-property-16.png"))); // NOI18N
        mActualizarCliente.setText("Actualizar");
        mActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActualizarClienteActionPerformed(evt);
            }
        });
        mClientes.add(mActualizarCliente);

        mListarClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/icons8-bullet-list-16.png"))); // NOI18N
        mListarClientes.setText("Todos");
        mListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mListarClientesActionPerformed(evt);
            }
        });
        mClientes.add(mListarClientes);

        menuBar.add(mClientes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarClienteActionPerformed
        GuardarCliente myForm = new GuardarCliente();
        myForm.setLocation(
                (panelPrincipal.getSize().width - myForm.getSize().width) / 2,
                (panelPrincipal.getSize().height - myForm.getSize().height) / 2
        );
        this.panelPrincipal.add(myForm);
        myForm.show();
    }//GEN-LAST:event_mRegistrarClienteActionPerformed

    private void mActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActualizarClienteActionPerformed
        ActualizarCliente myForm = new ActualizarCliente();
        myForm.setLocation(
                (panelPrincipal.getSize().width - myForm.getSize().width) / 2,
                (panelPrincipal.getSize().height - myForm.getSize().height) / 2
        );
        this.panelPrincipal.add(myForm);
        myForm.show();
    }//GEN-LAST:event_mActualizarClienteActionPerformed

    private void mListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mListarClientesActionPerformed
        ListarCliente myForm = new ListarCliente();
        myForm.setLocation(
                (panelPrincipal.getSize().width - myForm.getSize().width) / 2,
                (panelPrincipal.getSize().height - myForm.getSize().height) / 2
        );
        this.panelPrincipal.add(myForm);
        myForm.show();
    }//GEN-LAST:event_mListarClientesActionPerformed

    private void mRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarUsuarioActionPerformed
        GuardarUsuario myForm = new GuardarUsuario();
        myForm.setLocation(
                (panelPrincipal.getSize().width - myForm.getSize().width) / 2,
                (panelPrincipal.getSize().height - myForm.getSize().height) / 2
        );
        this.panelPrincipal.add(myForm);
        myForm.show();
    }//GEN-LAST:event_mRegistrarUsuarioActionPerformed

    private void mActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActualizarUsuarioActionPerformed
        ActualizarUsuario myForm = new ActualizarUsuario();
        myForm.setLocation(
                (panelPrincipal.getSize().width - myForm.getSize().width) / 2,
                (panelPrincipal.getSize().height - myForm.getSize().height) / 2
        );
        this.panelPrincipal.add(myForm);
        myForm.show();
    }//GEN-LAST:event_mActualizarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem mActualizarCliente;
    private javax.swing.JMenuItem mActualizarUsuario;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mEstudiante;
    private javax.swing.JMenu mInicio;
    private javax.swing.JMenuItem mListarClientes;
    private javax.swing.JMenu mMatricula;
    private javax.swing.JMenuItem mRegistrarCliente;
    private javax.swing.JMenuItem mRegistrarUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opCarrera;
    private javax.swing.JMenuItem opGrupo;
    private javax.swing.JMenuItem opPeriodo;
    private javax.swing.JDesktopPane panelPrincipal;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables
}
